# Generated by Django 4.1.5 on 2024-02-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=199)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
